
/* Drop Indexes */

DROP INDEX IF EXISTS WDIDX_Adresse_ADR_VILLAGE;
DROP INDEX IF EXISTS WDIDX_CompteBanc_CB_BANQUE;
DROP INDEX IF EXISTS WDIDX_CompteBanc_CB_BEDUT;
DROP INDEX IF EXISTS WDIDX_CompteBanc_CB_FIN;
DROP INDEX IF EXISTS WDIDX_CompteBanc_CB_GUICHET;
DROP INDEX IF EXISTS WDIDX_CompteBanc_CB_INDIVIDU;
DROP INDEX IF EXISTS WDIDX_Couple_CPL_FEMME;
DROP INDEX IF EXISTS WDIDX_Couple_CPL_FEMMECPL_MARI;
DROP INDEX IF EXISTS WDIDX_Couple_CPL_MARI;
DROP INDEX IF EXISTS WDIDX_DECISION_DEC_ATRIBUTAIRE;
DROP INDEX IF EXISTS WDIDX_DECISION_DEC_COMMISSION;
DROP INDEX IF EXISTS WDIDX_DECISION_DEC_DEMANNUELLE;
DROP INDEX IF EXISTS WDIDX_DECISION_DEC_NO;
DROP INDEX IF EXISTS WDIDX_Decision_GIR_DCGIR_COMMISSION;
DROP INDEX IF EXISTS WDIDX_Decision_GIR_DCGIR_GIR;
DROP INDEX IF EXISTS WDIDX_Decision_GIR_DCGIR_INDIVIDU;
DROP INDEX IF EXISTS WDIDX_DemAnnuelle_DEMA_DAMANDEGLB;
DROP INDEX IF EXISTS WDIDX_DemAnnuelle_DEMA_DEBUT;
DROP INDEX IF EXISTS WDIDX_DemAnnuelle_DEMA_FIN;
DROP INDEX IF EXISTS WDIDX_DemGlobal_DEMG_INDIVIDU;
DROP INDEX IF EXISTS WDIDX_DemGlobal_DEMG_TYPE_AIDE;
DROP INDEX IF EXISTS WDIDX_Guichet_GT_BANQUE;
DROP INDEX IF EXISTS WDIDX_Habite_HAB_ADRESSE;
DROP INDEX IF EXISTS WDIDX_Habite_HAB_DEBUT;
DROP INDEX IF EXISTS WDIDX_Habite_HAB_FIN;
DROP INDEX IF EXISTS WDIDX_Habite_HAB_INDIVIDU;
DROP INDEX IF EXISTS WDIDX_Handicap_IHAND_DEBUT;
DROP INDEX IF EXISTS WDIDX_Handicap_IHAND_FIN;
DROP INDEX IF EXISTS WDIDX_Handicap_IHAND_INDIVIDU;
DROP INDEX IF EXISTS WDIDX_Handicap_IHAND_TYPEHAND;
DROP INDEX IF EXISTS WDIDX_Individu_IND_MERE;
DROP INDEX IF EXISTS WDIDX_Individu_IND_NEA;
DROP INDEX IF EXISTS WDIDX_Individu_IND_PERE;
DROP INDEX IF EXISTS WDIDX_Individu_IND_SituFam;
DROP INDEX IF EXISTS WDIDX_PieceAfournir_PAF_PIECE;
DROP INDEX IF EXISTS WDIDX_PieceAfournir_PAF_TYPEAIDE;
DROP INDEX IF EXISTS WDIDX_PieceFourni_PF_DEMANNUELLE;
DROP INDEX IF EXISTS WDIDX_PieceFourni_PF_PIECE;
DROP INDEX IF EXISTS WDIDX_RattFisc_RAT_ENFANT;
DROP INDEX IF EXISTS WDIDX_RattFisc_RAT_PARENT;
DROP INDEX IF EXISTS WDIDX_RevenuCharge_RC_INDIVIDU;
DROP INDEX IF EXISTS WDIDX_RevenuCharge_RC_RESSOURCE;
DROP INDEX IF EXISTS WDIDX_Typeaide_TYPEA_AIDE_RELAIS;
DROP INDEX IF EXISTS WDIDX_Valoris_GIR_GIR_CODE;
DROP INDEX IF EXISTS WDIDX_Village_VIL_COMMUNE;
DROP INDEX IF EXISTS WDIDX_Village_VIL_NINSEE;



/* Drop Tables */

DROP TABLE IF EXISTS new_table;
DROP TABLE IF EXISTS public.Habite;
DROP TABLE IF EXISTS public.Adresse;
DROP TABLE IF EXISTS public.CompteBanc;
DROP TABLE IF EXISTS public.Guichet;
DROP TABLE IF EXISTS public.Banque;
DROP TABLE IF EXISTS public.Decision_GIR;
DROP TABLE IF EXISTS public.DECISION;
DROP TABLE IF EXISTS public.COMMISSION;
DROP TABLE IF EXISTS public.Couple;
DROP TABLE IF EXISTS public.RattFisc;
DROP TABLE IF EXISTS public.PieceFourni;
DROP TABLE IF EXISTS public.DemAnnuelle;
DROP TABLE IF EXISTS public.DemGlobal;
DROP TABLE IF EXISTS public.RevenuCharge;
DROP TABLE IF EXISTS public.Handicap;
DROP TABLE IF EXISTS public.Individu;
DROP TABLE IF EXISTS public.Village;
DROP TABLE IF EXISTS public.Commune;
DROP TABLE IF EXISTS public.COMPTEUR;
DROP TABLE IF EXISTS public.Valoris_GIR;
DROP TABLE IF EXISTS public.GIR;
DROP TABLE IF EXISTS public.PieceAfournir;
DROP TABLE IF EXISTS public.Pieces;
DROP TABLE IF EXISTS public.Ressource;
DROP TABLE IF EXISTS public.SituFam;
DROP TABLE IF EXISTS public.typeaide;
DROP TABLE IF EXISTS public.Type_handicap;



/* Drop Sequences */

DROP SEQUENCE IF EXISTS public.Adresse_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Banque_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.COMMISSION_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Commune_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.CompteBanc_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Couple_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.DECISION_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Decision_GIR_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.DemAnnuelle_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.DemGlobal_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Guichet_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Handicap_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Individu_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.PieceAfournir_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.PieceFourni_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Pieces_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.RattFisc_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Ressource_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.RevenuCharge_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.SituFam_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.typeaide_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Type_handicap_Cle_id_seq;
DROP SEQUENCE IF EXISTS public.Village_Cle_id_seq;




/* Create Tables */

CREATE TABLE new_table
(

) WITHOUT OIDS;


CREATE TABLE public.Adresse
(
	Cle_id serial NOT NULL,
	ADR_NUM varchar(5),
	ADR_RUE varchar(250),
	ADR_CP varchar(5),
	ADR_VILLAGE int,
	CONSTRAINT Adresse_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Banque
(
	Cle_id serial NOT NULL,
	BQ_CODE varchar(6),
	BQ_LIBELLE varchar(100),
	CONSTRAINT Banque_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.COMMISSION
(
	COM_CODE varchar(17) NOT NULL UNIQUE,
	COM_DATE date NOT NULL,
	COM_HEURE time NOT NULL,
	COM_LIEU varchar(135) NOT NULL,
	Cle_id serial NOT NULL,
	COM_MEMBRES text NOT NULL,
	CONSTRAINT COMMISSION_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Commune
(
	Cle_id serial NOT NULL,
	CMN_INSEE varchar(50),
	CMN_NOM varchar(150),
	CONSTRAINT Commune_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.CompteBanc
(
	Cle_id serial NOT NULL,
	CB_NUMCPT varchar(11),
	CB_CLE varchar(2),
	CB_BEDUT date,
	CB_FIN date,
	CB_INDIVIDU int,
	CB_IBAN varchar(50),
	CB_GUICHET int,
	CB_BANQUE int,
	CONSTRAINT CompteBanc_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.COMPTEUR
(
	NOM_TABLE varchar(35) NOT NULL,
	DERNIER_NUMERO int DEFAULT 0 NOT NULL,
	AVECPREFIXE boolean DEFAULT 'false' NOT NULL,
	PREFIXE varchar(8) NOT NULL
) WITHOUT OIDS;


CREATE TABLE public.Couple
(
	CPL_FEMME int DEFAULT 0,
	CPL_MARI int DEFAULT 0,
	Cle_id serial NOT NULL,
	CPL_DEBUT date,
	CPL_fIN date,
	CONSTRAINT Couple_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.DECISION
(
	DEC_NO varchar(17) NOT NULL,
	Cle_id serial NOT NULL,
	DEC_AVIS smallint DEFAULT 0 NOT NULL,
	DEC_DEMANNUELLE int NOT NULL,
	DEC_COMMISSION int NOT NULL,
	DEC_ATRIBUTAIRE int NOT NULL,
	CONSTRAINT DECISION_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Decision_GIR
(
	DCGIR_DATE_DEBUT date NOT NULL,
	DCGIR_DATE_FIN date NOT NULL,
	Cle_id serial NOT NULL,
	DCGIR_INDIVIDU int NOT NULL,
	DCGIR_COMMISSION int NOT NULL,
	DCGIR_GIR varchar(2) NOT NULL,
	CONSTRAINT Decision_GIR_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.DemAnnuelle
(
	Cle_id serial NOT NULL,
	DEMA_DEBUT date,
	DEMA_FIN date,
	DEMA_ETAT smallint DEFAULT 0,
	DEMA_STATUT smallint DEFAULT 0,
	DEMA_DAMANDEGLB int,
	DEMA_MONTANT_EST numeric(24,6) DEFAULT 0,
	CONSTRAINT DemAnnuelle_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.DemGlobal
(
	Cle_id serial NOT NULL,
	DEMG_CODE varchar(10),
	DEMG_DATE date,
	DEMG_DATEFINPREVUE date,
	DEMG_STATUT smallint DEFAULT 0,
	DEMG_ETAT smallint DEFAULT 0,
	DEMG_INDIVIDU int,
	DEMG_TYPE_AIDE int,
	DEMG_DOSSIER varchar(15),
	DEMG_TYE varchar(10),
	CONSTRAINT DemGlobal_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.GIR
(
	GIR_CODE varchar(2) DEFAULT '''0''::character varying' NOT NULL UNIQUE,
	GIR_DESIGNATION varchar(50) NOT NULL
) WITHOUT OIDS;


CREATE TABLE public.Guichet
(
	Cle_id serial NOT NULL,
	GT_CODE varchar(6),
	GT_LIBELLE varchar(100),
	GT_BANQUE int,
	CONSTRAINT Guichet_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Habite
(
	HAB_DEBUT date,
	HAB_FIN date,
	HAB_ADRESSE int,
	HAB_INDIVIDU int
) WITHOUT OIDS;


CREATE TABLE public.Handicap
(
	Cle_id serial NOT NULL,
	IHAND_DEBUT date,
	IHAND_FIN date,
	IHAND_INDIVIDU int DEFAULT 0,
	IHAND_TYPEHAND int DEFAULT 0,
	CONSTRAINT Handicap_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Individu
(
	Cle_id serial NOT NULL,
	IND_MATRICULE varchar(10),
	IND_NOM varchar(50),
	IND_PRENOM varchar(50),
	IND_TELFIXE varchar(10),
	IND_DDN date,
	IND_GSM1 varchar(10),
	IND_GSM2 varchar(10),
	IND_EMAIL varchar(10),
	IND_SituFam int DEFAULT 0,
	IND_CIVILITE smallint DEFAULT 0,
	IND_PERE int DEFAULT 0,
	IND_MERE int DEFAULT 0,
	IND_NATIONALITE smallint DEFAULT 0,
	IND_NEA int DEFAULT 0,
	IND_TIERS varchar(10),
	CONSTRAINT Individu_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.PieceAfournir
(
	Cle_id serial NOT NULL,
	PAF_ETAPE varchar(1),
	PAF_TYPEAIDE int,
	PAF_PIECE int,
	CONSTRAINT PieceAfournir_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.PieceFourni
(
	Cle_id serial NOT NULL,
	PF_POINTE boolean DEFAULT 'false',
	PF_DEMANNUELLE int,
	PF_PIECE int,
	CONSTRAINT PieceFourni_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Pieces
(
	Cle_id serial NOT NULL,
	PC_CODE varchar(5),
	PC_LIBELLE varchar(150),
	CONSTRAINT Pieces_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.RattFisc
(
	Cle_id serial NOT NULL,
	RAT_DEBUT date,
	RAT_FIN date,
	RAT_PARENT int,
	RAT_ENFANT int,
	CONSTRAINT RattFisc_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Ressource
(
	Cle_id serial NOT NULL,
	RES_CODE varchar(10),
	RES_LIBELLE varchar(150),
	RES_TYPE smallint DEFAULT 0,
	CONSTRAINT Ressource_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.RevenuCharge
(
	Cle_id serial NOT NULL,
	RC_DEBUT date,
	RC_FIN date UNIQUE,
	RC_MONTANT numeric(24,6) DEFAULT 0,
	RC_INDIVIDU int,
	RC_RESSOURCE int,
	CONSTRAINT RevenuCharge_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.SituFam
(
	Cle_id serial NOT NULL,
	SF_CODE varchar(10),
	SF_LIBELLE varchar(100),
	SF_COUPLE boolean DEFAULT 'false',
	CONSTRAINT SituFam_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.typeaide
(
	TYPEA_CODE varchar(5) NOT NULL UNIQUE,
	TYPEA_LIBELLE varchar(50) NOT NULL,
	TYPEA_IMPUTATION varchar(10) NOT NULL,
	TYPEA_AGE_LIMITE int DEFAULT 0 NOT NULL,
	TYPEA_AGE_MINI int DEFAULT 0 NOT NULL,
	TYPEA_MODE_PAIE varchar(50) NOT NULL,
	Cle_id serial NOT NULL,
	TYPEA_AIDE_RELAIS int DEFAULT 0 NOT NULL,
	CONSTRAINT typeaide_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Type_handicap
(
	Cle_id serial NOT NULL,
	HAND_CODE varchar(10),
	HAND_LIBELLE varchar(150),
	CONSTRAINT Type_handicap_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;


CREATE TABLE public.Valoris_GIR
(
	DATE_DEBUT date NOT NULL,
	DATE_FIN date NOT NULL,
	GIR_CODE varchar(2) NOT NULL,
	Valeur numeric(24,6) DEFAULT 0 NOT NULL
) WITHOUT OIDS;


CREATE TABLE public.Village
(
	Cle_id serial NOT NULL,
	VIL_NOM varchar(100),
	VIL_NINSEE varchar(50) DEFAULT 'NULL::character varying',
	VIL_CP varchar(5),
	VIL_COMMUNE int,
	CONSTRAINT Village_pkey PRIMARY KEY (Cle_id)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE public.Habite
	ADD CONSTRAINT Habite_HAB_ADRESSE_fkey FOREIGN KEY (HAB_ADRESSE)
	REFERENCES public.Adresse (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.CompteBanc
	ADD CONSTRAINT CompteBanc_CB_BANQUE_fkey FOREIGN KEY (CB_BANQUE)
	REFERENCES public.Banque (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Guichet
	ADD CONSTRAINT Guichet_GT_BANQUE_fkey FOREIGN KEY (GT_BANQUE)
	REFERENCES public.Banque (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Decision_GIR
	ADD CONSTRAINT Decision_GIR_DCGIR_COMMISSION_fkey FOREIGN KEY (DCGIR_COMMISSION)
	REFERENCES public.COMMISSION (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.DECISION
	ADD CONSTRAINT DECISION_DEC_COMMISSION_fkey FOREIGN KEY (DEC_COMMISSION)
	REFERENCES public.COMMISSION (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Village
	ADD CONSTRAINT Village_VIL_COMMUNE_fkey FOREIGN KEY (VIL_COMMUNE)
	REFERENCES public.Commune (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.DECISION
	ADD CONSTRAINT DECISION_DEC_DEMANNUELLE_fkey FOREIGN KEY (DEC_DEMANNUELLE)
	REFERENCES public.DemAnnuelle (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.PieceFourni
	ADD CONSTRAINT PieceFourni_PF_DEMANNUELLE_fkey FOREIGN KEY (PF_DEMANNUELLE)
	REFERENCES public.DemAnnuelle (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.DemAnnuelle
	ADD CONSTRAINT DemAnnuelle_DEMA_DAMANDEGLB_fkey FOREIGN KEY (DEMA_DAMANDEGLB)
	REFERENCES public.DemGlobal (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Decision_GIR
	ADD CONSTRAINT Decision_GIR_DCGIR_GIR_fkey FOREIGN KEY (DCGIR_GIR)
	REFERENCES public.GIR (GIR_CODE)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Valoris_GIR
	ADD CONSTRAINT Valoris_GIR_GIR_CODE_fkey FOREIGN KEY (GIR_CODE)
	REFERENCES public.GIR (GIR_CODE)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.CompteBanc
	ADD CONSTRAINT CompteBanc_CB_GUICHET_fkey FOREIGN KEY (CB_GUICHET)
	REFERENCES public.Guichet (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.DECISION
	ADD CONSTRAINT DECISION_DEC_ATRIBUTAIRE_fkey FOREIGN KEY (DEC_ATRIBUTAIRE)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Decision_GIR
	ADD CONSTRAINT Decision_GIR_DCGIR_INDIVIDU_fkey FOREIGN KEY (DCGIR_INDIVIDU)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Individu
	ADD CONSTRAINT Individu_IND_MERE_fkey FOREIGN KEY (IND_MERE)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Couple
	ADD CONSTRAINT Couple_CPL_MARI_fkey FOREIGN KEY (CPL_MARI)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.RattFisc
	ADD CONSTRAINT RattFisc_RAT_PARENT_fkey FOREIGN KEY (RAT_PARENT)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Couple
	ADD CONSTRAINT Couple_CPL_FEMME_fkey FOREIGN KEY (CPL_FEMME)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.RattFisc
	ADD CONSTRAINT RattFisc_RAT_ENFANT_fkey FOREIGN KEY (RAT_ENFANT)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.DemGlobal
	ADD CONSTRAINT DemGlobal_DEMG_INDIVIDU_fkey FOREIGN KEY (DEMG_INDIVIDU)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.RevenuCharge
	ADD CONSTRAINT RevenuCharge_RC_INDIVIDU_fkey FOREIGN KEY (RC_INDIVIDU)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Handicap
	ADD CONSTRAINT Handicap_IHAND_INDIVIDU_fkey FOREIGN KEY (IHAND_INDIVIDU)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Habite
	ADD CONSTRAINT Habite_HAB_INDIVIDU_fkey FOREIGN KEY (HAB_INDIVIDU)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Individu
	ADD CONSTRAINT Individu_IND_PERE_fkey FOREIGN KEY (IND_PERE)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.CompteBanc
	ADD CONSTRAINT CompteBanc_CB_INDIVIDU_fkey FOREIGN KEY (CB_INDIVIDU)
	REFERENCES public.Individu (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.PieceFourni
	ADD CONSTRAINT PieceFourni_PF_PIECE_fkey FOREIGN KEY (PF_PIECE)
	REFERENCES public.Pieces (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.PieceAfournir
	ADD CONSTRAINT PieceAfournir_PAF_PIECE_fkey FOREIGN KEY (PAF_PIECE)
	REFERENCES public.Pieces (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.RevenuCharge
	ADD CONSTRAINT RevenuCharge_RC_RESSOURCE_fkey FOREIGN KEY (RC_RESSOURCE)
	REFERENCES public.Ressource (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Individu
	ADD CONSTRAINT Individu_IND_SituFam_fkey FOREIGN KEY (IND_SituFam)
	REFERENCES public.SituFam (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.typeaide
	ADD CONSTRAINT typeaide_TYPEA_AIDE_RELAIS_fkey FOREIGN KEY (TYPEA_AIDE_RELAIS)
	REFERENCES public.typeaide (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.PieceAfournir
	ADD CONSTRAINT PieceAfournir_PAF_TYPEAIDE_fkey FOREIGN KEY (PAF_TYPEAIDE)
	REFERENCES public.typeaide (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.DemGlobal
	ADD CONSTRAINT DemGlobal_DEMG_TYPE_AIDE_fkey FOREIGN KEY (DEMG_TYPE_AIDE)
	REFERENCES public.typeaide (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Handicap
	ADD CONSTRAINT Handicap_IHAND_TYPEHAND_fkey FOREIGN KEY (IHAND_TYPEHAND)
	REFERENCES public.Type_handicap (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Individu
	ADD CONSTRAINT Individu_IND_NEA_fkey FOREIGN KEY (IND_NEA)
	REFERENCES public.Village (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE public.Adresse
	ADD CONSTRAINT Adresse_ADR_VILLAGE_fkey FOREIGN KEY (ADR_VILLAGE)
	REFERENCES public.Village (Cle_id)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;



/* Create Indexes */

CREATE INDEX WDIDX_Adresse_ADR_VILLAGE ON public.Adresse USING BTREE (ADR_VILLAGE);
CREATE INDEX WDIDX_CompteBanc_CB_BANQUE ON public.CompteBanc USING BTREE (CB_BANQUE);
CREATE INDEX WDIDX_CompteBanc_CB_BEDUT ON public.CompteBanc USING BTREE (CB_BEDUT);
CREATE INDEX WDIDX_CompteBanc_CB_FIN ON public.CompteBanc USING BTREE (CB_FIN);
CREATE INDEX WDIDX_CompteBanc_CB_GUICHET ON public.CompteBanc USING BTREE (CB_GUICHET);
CREATE INDEX WDIDX_CompteBanc_CB_INDIVIDU ON public.CompteBanc USING BTREE (CB_INDIVIDU);
CREATE INDEX WDIDX_Couple_CPL_FEMME ON public.Couple USING BTREE (CPL_FEMME);
CREATE INDEX WDIDX_Couple_CPL_FEMMECPL_MARI ON public.Couple USING BTREE (CPL_FEMME, CPL_MARI);
CREATE INDEX WDIDX_Couple_CPL_MARI ON public.Couple USING BTREE (CPL_MARI);
CREATE INDEX WDIDX_DECISION_DEC_ATRIBUTAIRE ON public.DECISION USING BTREE (DEC_ATRIBUTAIRE);
CREATE INDEX WDIDX_DECISION_DEC_COMMISSION ON public.DECISION USING BTREE (DEC_COMMISSION);
CREATE INDEX WDIDX_DECISION_DEC_DEMANNUELLE ON public.DECISION USING BTREE (DEC_DEMANNUELLE);
CREATE INDEX WDIDX_DECISION_DEC_NO ON public.DECISION USING BTREE (DEC_NO);
CREATE INDEX WDIDX_Decision_GIR_DCGIR_COMMISSION ON public.Decision_GIR USING BTREE (DCGIR_COMMISSION);
CREATE INDEX WDIDX_Decision_GIR_DCGIR_GIR ON public.Decision_GIR USING BTREE (DCGIR_GIR);
CREATE INDEX WDIDX_Decision_GIR_DCGIR_INDIVIDU ON public.Decision_GIR USING BTREE (DCGIR_INDIVIDU);
CREATE INDEX WDIDX_DemAnnuelle_DEMA_DAMANDEGLB ON public.DemAnnuelle USING BTREE (DEMA_DAMANDEGLB);
CREATE INDEX WDIDX_DemAnnuelle_DEMA_DEBUT ON public.DemAnnuelle USING BTREE (DEMA_DEBUT);
CREATE INDEX WDIDX_DemAnnuelle_DEMA_FIN ON public.DemAnnuelle USING BTREE (DEMA_FIN);
CREATE INDEX WDIDX_DemGlobal_DEMG_INDIVIDU ON public.DemGlobal USING BTREE (DEMG_INDIVIDU);
CREATE INDEX WDIDX_DemGlobal_DEMG_TYPE_AIDE ON public.DemGlobal USING BTREE (DEMG_TYPE_AIDE);
CREATE INDEX WDIDX_Guichet_GT_BANQUE ON public.Guichet USING BTREE (GT_BANQUE);
CREATE INDEX WDIDX_Habite_HAB_ADRESSE ON public.Habite USING BTREE (HAB_ADRESSE);
CREATE INDEX WDIDX_Habite_HAB_DEBUT ON public.Habite USING BTREE (HAB_DEBUT);
CREATE INDEX WDIDX_Habite_HAB_FIN ON public.Habite USING BTREE (HAB_FIN);
CREATE INDEX WDIDX_Habite_HAB_INDIVIDU ON public.Habite USING BTREE (HAB_INDIVIDU);
CREATE INDEX WDIDX_Handicap_IHAND_DEBUT ON public.Handicap USING BTREE (IHAND_DEBUT);
CREATE INDEX WDIDX_Handicap_IHAND_FIN ON public.Handicap USING BTREE (IHAND_FIN);
CREATE INDEX WDIDX_Handicap_IHAND_INDIVIDU ON public.Handicap USING BTREE (IHAND_INDIVIDU);
CREATE INDEX WDIDX_Handicap_IHAND_TYPEHAND ON public.Handicap USING BTREE (IHAND_TYPEHAND);
CREATE INDEX WDIDX_Individu_IND_MERE ON public.Individu USING BTREE (IND_MERE);
CREATE INDEX WDIDX_Individu_IND_NEA ON public.Individu USING BTREE (IND_NEA);
CREATE INDEX WDIDX_Individu_IND_PERE ON public.Individu USING BTREE (IND_PERE);
CREATE INDEX WDIDX_Individu_IND_SituFam ON public.Individu USING BTREE (IND_SituFam);
CREATE INDEX WDIDX_PieceAfournir_PAF_PIECE ON public.PieceAfournir USING BTREE (PAF_PIECE);
CREATE INDEX WDIDX_PieceAfournir_PAF_TYPEAIDE ON public.PieceAfournir USING BTREE (PAF_TYPEAIDE);
CREATE INDEX WDIDX_PieceFourni_PF_DEMANNUELLE ON public.PieceFourni USING BTREE (PF_DEMANNUELLE);
CREATE INDEX WDIDX_PieceFourni_PF_PIECE ON public.PieceFourni USING BTREE (PF_PIECE);
CREATE INDEX WDIDX_RattFisc_RAT_ENFANT ON public.RattFisc USING BTREE (RAT_ENFANT);
CREATE INDEX WDIDX_RattFisc_RAT_PARENT ON public.RattFisc USING BTREE (RAT_PARENT);
CREATE INDEX WDIDX_RevenuCharge_RC_INDIVIDU ON public.RevenuCharge USING BTREE (RC_INDIVIDU);
CREATE INDEX WDIDX_RevenuCharge_RC_RESSOURCE ON public.RevenuCharge USING BTREE (RC_RESSOURCE);
CREATE INDEX WDIDX_Typeaide_TYPEA_AIDE_RELAIS ON public.typeaide USING BTREE (TYPEA_AIDE_RELAIS);
CREATE INDEX WDIDX_Valoris_GIR_GIR_CODE ON public.Valoris_GIR USING BTREE (GIR_CODE);
CREATE INDEX WDIDX_Village_VIL_COMMUNE ON public.Village USING BTREE (VIL_COMMUNE);
CREATE INDEX WDIDX_Village_VIL_NINSEE ON public.Village USING BTREE (VIL_NINSEE);



